# Generated by Django 5.2.2 on 2025-07-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "category", "purchase_price"],
                "permissions": [
                    ("can_unpublish_product", "Может отменять публикацию продукта"),
                    ("can_delete_any_product", "Может удалять любой продукт"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("draft", "Черновик"), ("published", "Опубликован"), ("rejected", "Отклонен")],
                default="draft",
                max_length=10,
                verbose_name="Статус публикации",
            ),
        ),
    ]
